#include "DebugOverlayBuilder.h"

#include "DebugFingerprint.h"
#include "DebugThresholds.h"

#include <filesystem>
#include <fstream>
#include <cstdio>
#include <cmath>
#include <regex>
#include <sstream>
#include <system_error>

namespace sigflow {
namespace debug {

namespace {

bool WriteFile(const std::string& path, const std::string& content, std::string& error)
{
    std::ofstream out(path, std::ios::trunc);
    if (!out) {
        error = "unable to write " + path;
        return false;
    }
    out.write(content.data(), static_cast<std::streamsize>(content.size()));
    out.flush();
    if (!out) {
        error = "unable to write " + path;
        return false;
    }
    return true;
}

std::string Hex64(uint64_t value)
{
    char buffer[17];
    std::snprintf(buffer, sizeof(buffer), "%016llx",
                  static_cast<unsigned long long>(value));
    return std::string(buffer);
}

std::string ReadTextFile(const std::filesystem::path& path)
{
    std::ifstream input(path, std::ios::binary);
    if (!input) return {};
    return std::string((std::istreambuf_iterator<char>(input)),
                       std::istreambuf_iterator<char>());
}

std::filesystem::path FindUserCst(const std::string& projectPath,
                                  const std::string& topModule,
                                  const std::string& configuredCstPath)
{
    const std::filesystem::path root(projectPath);
    if (!configuredCstPath.empty()) {
        const std::filesystem::path configured(configuredCstPath);
        return configured.is_absolute() ? configured : root / configured;
    }
    const std::vector<std::filesystem::path> preferred = {
        root / "constraints" / (topModule + ".cst"),
        root / "constraints" / "tangnano9k.cst",
        root / "nextpnr" / (topModule + ".cst")
    };
    for (const auto& path : preferred) {
        if (std::filesystem::is_regular_file(path)) return path;
    }
    for (const auto& directory : { root / "constraints", root / "nextpnr" }) {
        if (!std::filesystem::is_directory(directory)) continue;
        for (const auto& entry : std::filesystem::directory_iterator(directory)) {
            if (entry.is_regular_file() && entry.path().extension() == ".cst") {
                return entry.path();
            }
        }
    }
    return {};
}

bool IsUartClockAccurate(std::uint64_t clockHz, std::uint32_t baud,
                         std::uint64_t& divider, double& errorPercent)
{
    if (clockHz == 0 || baud == 0) return false;
    divider = (clockHz + baud / 2) / baud;
    if (divider == 0) divider = 1;
    const double actualBaud = static_cast<double>(clockHz) /
                              static_cast<double>(divider);
    errorPercent = std::abs(actualBaud - static_cast<double>(baud)) * 100.0 /
                   static_cast<double>(baud);
    return errorPercent <= 2.5;
}

int Clog2(int value)
{
    int bits = 0;
    int v = value - 1;
    while (v > 0) {
        v >>= 1;
        ++bits;
    }
    return bits;
}

} // namespace

bool DebugOverlayBuilder::SnapshotUserSources(
    const std::vector<std::string>& files,
    std::map<std::string, std::string>& before, std::string& error) const
{
    before.clear();
    for (const std::string& file : files) {
        const std::string hash = Sha256File(file);
        if (hash.empty()) {
            error = "unable to hash user source: " + file;
            return false;
        }
        before[file] = hash;
    }
    return true;
}

bool DebugOverlayBuilder::VerifyUserSourcesUntouched(
    const std::map<std::string, std::string>& before, std::string& error) const
{
    for (const auto& [path, expected] : before) {
        const std::string hash = Sha256File(path);
        if (hash != expected) {
            error = "user source changed during debug build: " + path;
            return false;
        }
    }
    return true;
}

std::string DebugOverlayBuilder::BuildWrapper(
    const DebugContract& contract,
    const std::vector<DebugPortInfo>& userTopPorts) const
{
    const std::string topName = contract.topModule;
    const std::string clkName = contract.sampleClock.signal;
    const char* linkModule = contract.transport.protocol == "full"
                                 ? "sf_debug_link"
                                 : "sf_debug_link_minimal";
    std::ostringstream out;

    out << "// Generated by SigFlow DebugOverlayBuilder — do not edit.\n";
    out << "// Session: " << contract.sessionId << "\n";
    out << "module sf_debug_top(\n";
    out << "    input  wire dbg_rx,\n";
    out << "    output wire dbg_tx,\n";
    const bool hasDebugResetPin = contract.transport.rstPin > 0;
    if (hasDebugResetPin) out << "    input  wire dbg_rst_n,\n";
    for (const DebugPortInfo& port : userTopPorts) {
        if (port.name == clkName) continue;  // 时钟端口最后单独声明
        const char* dir = port.direction == "input" ? "input "
                          : port.direction == "inout" ? "inout "
                                                      : "output";
        out << "    " << dir << " wire";
        if (port.width > 1) out << " [" << (port.width - 1) << ":0]";
        out << " " << port.name << ",\n";
    }
    out << "    input  wire " << clkName << "\n";
    out << ");\n";
    if (!hasDebugResetPin) out << "    wire dbg_rst_n = 1'b1;\n";

    // 用户 DUT 例化
    out << "    " << topName << " u_dut (\n";
    for (const DebugPortInfo& port : userTopPorts) {
        if (port.name == clkName) continue;
        out << "        ." << port.name << "(" << port.name << "),\n";
    }
    out << "        ." << clkName << "(" << clkName << ")\n";
    out << "    );\n\n";

    // 探针总线（keep 保留）
    out << "    (* keep *) wire [31:0] probe_bus;\n";
    auto resolveSignal = [&](const std::string& path) -> std::string {
        std::string ref = path;
        if (!topName.empty() && ref.rfind(topName + ".", 0) == 0) {
            ref = ref.substr(topName.size() + 1);
        }
        bool isPort = false;
        for (const DebugPortInfo& port : userTopPorts) {
            if (port.name == ref) {
                isPort = true;
                break;
            }
        }
        if (!isPort) ref = "u_dut." + ref;
        return ref;
    };
    for (const DebugProbe& probe : contract.probes) {
        // 信号引用：顶层端口直接用端口名，否则 u_dut.<路径去掉顶层前缀>
        const std::string ref = resolveSignal(probe.path);
        out << "    assign probe_bus[" << (probe.bitOffset + probe.width - 1)
            << ":" << probe.bitOffset << "] = " << ref << ";\n";
    }

    // 采样时钟
    out << "    wire sample_clk = " << clkName << ";\n\n";

    // 桥接线
    out << "    wire arm, reset_pulse;\n";
    out << "    wire [31:0] trigger_mask, trigger_value;\n";
    out << "    wire [7:0] decimation;\n";
    out << "    wire busy, done, triggered;\n";
    const int aw = Clog2(static_cast<int>(contract.capture.depth));
    out << "    wire [" << (aw - 1) << ":0] trigger_index;\n";
    out << "    wire [" << (aw - 1) << ":0] rd_addr;\n";
    out << "    wire [31:0] rd_data;\n\n";
    out << "    wire [2:0] trigger_mode;\n";
    out << "    wire [15:0] trigger_count;\n";
    out << "    wire sample_en;\n";
    out << "    wire hs_valid, hs_ready;\n\n";

    // 握手超时触发信号（契约路径；空则保持核内默认）
    if (contract.trigger.hsValidPath.empty()) {
        out << "    assign hs_valid = 1'b0;\n";
    } else {
        out << "    assign hs_valid = " << resolveSignal(contract.trigger.hsValidPath) << ";\n";
    }
    if (contract.trigger.hsReadyPath.empty()) {
        out << "    assign hs_ready = 1'b1;\n";
    } else {
        out << "    assign hs_ready = " << resolveSignal(contract.trigger.hsReadyPath) << ";\n";
    }
    out << "\n";

    // sf_micro_ila
    out << "    sf_micro_ila #(.DEPTH(" << contract.capture.depth
        << "), .WIDTH(32)) u_ila (\n";
    out << "        .clk(sample_clk), .rst_n(dbg_rst_n),\n";
    out << "        .probe(probe_bus),\n";
    out << "        .arm(arm),\n";
    out << "        .trigger_mask(trigger_mask), .trigger_value(trigger_value),\n";
    out << "        .trigger_mode(trigger_mode), .trigger_count(trigger_count),\n";
    out << "        .decimation(decimation),\n";
    out << "        .sample_en(sample_en), .hs_valid(hs_valid), .hs_ready(hs_ready),\n";
    out << "        .busy(busy), .done(done), .triggered(triggered),\n";
    out << "        .rd_addr(rd_addr), .rd_data(rd_data),\n";
    out << "        .trigger_index(trigger_index)\n";
    out << "    );\n\n";

    // UART 调试链路：默认最小固定帧档，full 档保留 COBS/CRC。
    out << "    " << linkModule << " #(\n";
    out << "        .CLK_HZ(" << contract.sampleClock.frequencyHz << "),\n";
    out << "        .BAUD(" << contract.transport.baud << "),\n";
    out << "        .WIDTH(32),\n";
    out << "        .DEPTH(" << contract.capture.depth << "),\n";
    out << "        .FINGERPRINT64(64'h" << Hex64(contract.fingerprints.fingerprint64)
        << "),\n";
    out << "        .IP_VERSION(1)\n";
    out << "    ) u_link (\n";
    out << "        .clk(sample_clk), .rst_n(dbg_rst_n),\n";
    out << "        .rx(dbg_rx), .tx(dbg_tx),\n";
    out << "        .arm_pulse(arm), .reset_pulse(reset_pulse),\n";
    out << "        .trigger_mask(trigger_mask), .trigger_value(trigger_value),\n";
    out << "        .decimation(decimation),\n";
    out << "        .trigger_mode(trigger_mode), .trigger_count(trigger_count),\n";
    out << "        .sample_en(sample_en),\n";
    out << "        .busy(busy), .done(done), .triggered(triggered),\n";
    out << "        .trigger_index(trigger_index),\n";
    out << "        .rd_addr(rd_addr), .rd_data(rd_data)\n";
    out << "    );\n";
    out << "endmodule\n";
    return out.str();
}

std::string DebugOverlayBuilder::BuildMergedCst(
    const DebugContract& contract, const std::string& projectPath,
    const std::string& configuredCstPath,
    const std::vector<DebugPortInfo>& userTopPorts, std::string& error) const
{
    const std::filesystem::path userCstPath =
        FindUserCst(projectPath, contract.topModule, configuredCstPath);
    if (userCstPath.empty()) {
        error = "找不到用户工程 CST 约束文件；调试构建不能丢失 clk 和普通 IO 约束。";
        return {};
    }
    const std::string userCst = ReadTextFile(userCstPath);
    if (userCst.empty()) {
        error = "无法读取用户工程 CST 约束文件: " + userCstPath.string();
        return {};
    }

    for (const auto& port : userTopPorts) {
        if (port.name == "dbg_rx" || port.name == "dbg_tx" || port.name == "dbg_rst_n") {
            error = "用户顶层端口与 TraceBridge 调试端口重名: " + port.name;
            return {};
        }
    }

    std::map<int, std::string> usedPins;
    std::map<std::string, int> usedPorts;
    const std::regex location(R"re(IO_LOC\s+"([^"]+)"\s+([0-9]+)\s*;)re");
    for (std::sregex_iterator it(userCst.begin(), userCst.end(), location), end;
         it != end; ++it) {
        const std::string port = (*it)[1].str();
        const int pin = std::stoi((*it)[2].str());
        if (usedPorts.find(port) != usedPorts.end()) {
            error = "用户 CST 内部端口重复约束: " + port;
            return {};
        }
        const auto [pinIt, inserted] = usedPins.emplace(pin, port);
        if (!inserted) {
            error = "用户 CST 内部管脚冲突: " + std::to_string(pin) + " 已被 " +
                    pinIt->second + " 和 " + port + " 使用";
            return {};
        }
        usedPorts.emplace(port, pin);
    }
    const std::pair<const char*, int> debugPins[] = {
        {"dbg_rx", contract.transport.rxPin},
        {"dbg_tx", contract.transport.txPin},
        {"dbg_rst_n", contract.transport.rstPin}
    };
    for (const auto& [port, pin] : debugPins) {
        if (pin <= 0) {
            if (std::string(port) != "dbg_rst_n") {
                error = std::string("TraceBridge UART ") + port + " 未分配管脚";
                return {};
            }
            continue;
        }
        const auto existing = usedPins.find(pin);
        if (existing != usedPins.end()) {
            error = std::string("TraceBridge UART 管脚冲突: ") + port + "=" +
                    std::to_string(pin) + ", 已被 " + existing->second + " 使用";
            return {};
        }
        usedPins.emplace(pin, port);
    }

    std::ostringstream out;
    out << "// Generated by SigFlow DebugOverlayBuilder — merged user/debug constraints.\n";
    out << "// User CST: " << userCstPath.string() << "\n";
    out << userCst;
    if (userCst.back() != '\n') out << '\n';
    out << "\n// TraceBridge debug pins\n";
    out << "IO_LOC \"dbg_rx\" " << contract.transport.rxPin << ";\n";
    out << "IO_PORT \"dbg_rx\" IO_TYPE=LVCMOS33;\n";
    out << "IO_LOC \"dbg_tx\" " << contract.transport.txPin << ";\n";
    out << "IO_PORT \"dbg_tx\" IO_TYPE=LVCMOS33;\n";
    if (contract.transport.rstPin > 0) {
        out << "IO_LOC \"dbg_rst_n\" " << contract.transport.rstPin << ";\n";
        out << "IO_PORT \"dbg_rst_n\" IO_TYPE=LVCMOS33;\n";
    }
    return out.str();
}

std::string DebugOverlayBuilder::BuildYosysScript(
    const DebugContract& contract, const std::vector<std::string>& userSourceFiles,
    const std::string& debugRtlDir, const std::string& overlayDir,
    const std::string& artifactsDir, const std::string& wrapperPath,
    bool stubLink) const
{
    std::ostringstream out;
    out << "# Generated by SigFlow DebugOverlayBuilder\n";
    out << "# Session: " << contract.sessionId << "\n";
    out << "read_verilog -sv " << debugRtlDir << "/sf_micro_ila.sv\n";
    out << "read_verilog -sv " << debugRtlDir << "/sf_uart_link.sv\n";
    if (stubLink) {
        std::string stub = overlayDir + "\\sf_debug_link.sv";
        for (char& c : stub)
            if (c == '\\') c = '/';
        out << "read_verilog -sv " << stub << "\n";
    } else {
        const char* linkRtl = contract.transport.protocol == "full"
                                  ? "sf_debug_link.sv"
                                  : "sf_debug_link_minimal.sv";
        out << "read_verilog -sv " << debugRtlDir << "/" << linkRtl << "\n";
    }
    for (const std::string& file : userSourceFiles) {
        std::string normalized = file;
        for (char& c : normalized)
            if (c == '\\') c = '/';
        out << "read_verilog " << normalized << "\n";
    }
    std::string wrapper = wrapperPath;
    for (char& c : wrapper)
        if (c == '\\') c = '/';
    out << "read_verilog -sv " << wrapper << "\n";
    out << "hierarchy -top sf_debug_top\n";
    out << "proc\n";
    out << "write_json " << artifactsDir << "/sf_debug_top.pre.json\n";
    out << "synth_gowin -family gw1n -top sf_debug_top\n";
    out << "write_json " << artifactsDir << "/sf_debug_top.json\n";
    return out.str();
}

std::string DebugOverlayBuilder::BuildLinkStub(const DebugContract& contract) const
{
    std::ostringstream out;
    const char* linkModule = contract.transport.protocol == "full"
                                 ? "sf_debug_link"
                                 : "sf_debug_link_minimal";
    out << "// Generated by SigFlow DebugOverlayBuilder — UART 调试链路占位实现\n";
    out << "// （真实链路模块由 C++ 行为模型验证，待接入仿真器后替换）\n";
    out << "module " << linkModule << " #(\n";
    out << "    parameter int CLK_HZ = " << contract.sampleClock.frequencyHz << ",\n";
    out << "    parameter int BAUD = " << contract.transport.baud << ",\n";
    out << "    parameter int WIDTH = 32,\n";
    out << "    parameter int DEPTH = " << contract.capture.depth << ",\n";
    out << "    parameter logic [63:0] FINGERPRINT64 = 64'h"
        << Hex64(contract.fingerprints.fingerprint64) << ",\n";
    out << "    parameter int IP_VERSION = 1,\n";
    out << "    parameter int DATA_BYTES = 4\n";
    out << ") (\n";
    out << "    input logic clk, input logic rst_n,\n";
    out << "    input logic rx, output logic tx,\n";
    out << "    output logic arm_pulse, output logic reset_pulse,\n";
    out << "    output logic [31:0] trigger_mask, output logic [31:0] trigger_value,\n";
    out << "    output logic [7:0] decimation,\n";
    out << "    output logic [2:0] trigger_mode, output logic [15:0] trigger_count,\n";
    out << "    output logic sample_en,\n";
    out << "    input logic busy, input logic done, input logic triggered,\n";
    out << "    input logic [$clog2(DEPTH)-1:0] trigger_index,\n";
    out << "    output logic [$clog2(DEPTH)-1:0] rd_addr, input logic [WIDTH-1:0] rd_data\n";
    out << ");\n";
    out << "    assign tx = rx;\n";
    out << "    assign arm_pulse = 1'b0;\n";
    out << "    assign reset_pulse = 1'b0;\n";
    out << "    assign trigger_mask = 32'hFFFFFFFF;\n";
    out << "    assign trigger_value = 32'h0;\n";
    out << "    assign decimation = 8'd1;\n";
    out << "    assign trigger_mode = 3'd0;\n";
    out << "    assign trigger_count = 16'd1;\n";
    out << "    assign sample_en = 1'b1;\n";
    out << "    assign rd_addr = '0;\n";
    out << "endmodule\n";
    return out.str();
}

bool DebugOverlayBuilder::GenerateOverlay(
    const DebugContract& contract, const std::string& projectPath,
    const std::string& sessionDir, const std::string& artifactsDir,
    const std::vector<std::string>& userSourceFiles,
    const std::vector<DebugPortInfo>& userTopPorts, const std::string& debugRtlDir,
    const std::string& device, const std::string& family, bool stubLink,
    const std::string& configuredCstPath,
    DebugOverlayResult& result, std::string& error) const
{
    if (!contract.Validate(error)) return false;
    if (userTopPorts.empty()) {
        error = "no user top ports provided";
        return false;
    }
    if (contract.UsesMultipleClockDomains()) {
        error = "多时钟 Overlay/分域回读尚未启用；请先选择单一采样时钟，或等待多时钟 TraceBridge 支持。";
        return false;
    }

    std::uint64_t uartDivider = 0;
    double uartErrorPercent = 0.0;
    if (!IsUartClockAccurate(contract.sampleClock.frequencyHz, contract.transport.baud,
                             uartDivider, uartErrorPercent)) {
        error = "UART 时钟/波特率误差超过 2.5%：clk=" +
                std::to_string(contract.sampleClock.frequencyHz) + ", baud=" +
                std::to_string(contract.transport.baud);
        return false;
    }

    const std::string overlayDir = sessionDir + "\\overlay";
    std::error_code ec;
    std::filesystem::create_directories(overlayDir, ec);
    std::filesystem::create_directories(artifactsDir, ec);

    result.wrapperPath = overlayDir + "\\sf_debug_top.sv";
    result.cstPath = overlayDir + "\\debug.cst";
    result.yosysScriptPath = sessionDir + "\\scripts\\run_yosys.ys";
    result.nextpnrArgsPath = sessionDir + "\\scripts\\nextpnr_args.txt";
    result.gowinPackArgsPath = sessionDir + "\\scripts\\gowin_pack_args.txt";
    result.netlistJsonPath = artifactsDir + "\\sf_debug_top.json";
    result.netlistCheckJsonPath = artifactsDir + "\\sf_debug_top.pre.json";
    result.fsPath = artifactsDir + "\\sf_debug_top.fs";

    std::filesystem::create_directories(sessionDir + "\\scripts", ec);

    const std::string mergedCst =
        BuildMergedCst(contract, projectPath, configuredCstPath, userTopPorts, error);
    if (mergedCst.empty()) return false;

    if (!WriteFile(result.wrapperPath, BuildWrapper(contract, userTopPorts), error) ||
        !WriteFile(result.cstPath, mergedCst, error) ||
        !WriteFile(result.yosysScriptPath,
                   BuildYosysScript(contract, userSourceFiles, debugRtlDir, overlayDir,
                                    artifactsDir, result.wrapperPath, stubLink),
                   error)) {
        return false;
    }
    if (stubLink) {
        const std::string stubPath = overlayDir + "\\sf_debug_link.sv";
        if (!WriteFile(stubPath, BuildLinkStub(contract), error)) return false;
        result.generatedFiles.push_back(stubPath);
    }

    // nextpnr / gowin_pack 参数
    {
        std::ostringstream out;
        out << "--json " << artifactsDir << "/sf_debug_top.json\n";
        out << "--write " << artifactsDir << "/sf_debug_top.pnr.json\n";
        out << "--device " << device << "\n";
        out << "--vopt family=" << family << "\n";
        out << "--vopt cst=" << result.cstPath << "\n";
        if (!WriteFile(result.nextpnrArgsPath, out.str(), error)) return false;
    }
    {
        std::ostringstream out;
        out << "-d " << family << " -o " << result.fsPath << " "
            << artifactsDir << "/sf_debug_top.pnr.json\n";
        if (!WriteFile(result.gowinPackArgsPath, out.str(), error)) return false;
    }

    result.generatedFiles = {
        result.wrapperPath, result.cstPath, result.yosysScriptPath,
        result.nextpnrArgsPath, result.gowinPackArgsPath,
    };
    return true;
}

} // namespace debug
} // namespace sigflow
