#include "YosysScriptGenerator.h"

#include <cctype>
#include <filesystem>
#include <system_error>

namespace eda {
namespace synth {
namespace {

const StrategyInfo kBaselineStrategy{"baseline", "1.0", "Baseline"};
const StrategyInfo kDebugStrategy{"debug", "1.0", "Debug"};
const StrategyInfo kResourceOptimizedStrategy{"resource_optimized", "1.0", "Resource optimized"};

bool IsValidVerilogIdentifier(const std::string& value) {
    if (value.empty()) return false;
    const unsigned char first = static_cast<unsigned char>(value[0]);
    if (!(std::isalpha(first) || value[0] == '_')) return false;
    for (char c : value) {
        const unsigned char ch = static_cast<unsigned char>(c);
        if (!(std::isalnum(ch) || c == '_' || c == '$')) return false;
    }
    return true;
}

std::string ToLower(std::string value) {
    for (char& c : value) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    return value;
}

bool NormalizeYosysPath(const std::string& path, std::string& normalizedPath,
                        std::string& errorMessage) {
    if (path.empty()) {
        errorMessage = "A Yosys file path must not be empty.";
        return false;
    }
    if (path.find_first_of("\r\n\"") != std::string::npos) {
        errorMessage = "A Yosys file path contains a forbidden control or quote character.";
        return false;
    }
    std::error_code error;
    const std::filesystem::path absolute =
        std::filesystem::absolute(std::filesystem::path(path), error);
    if (error) {
        errorMessage = "Unable to normalize Yosys file path: " + path;
        return false;
    }
    const std::string generic = absolute.lexically_normal().generic_string();
    if (generic.empty()) {
        errorMessage = "Unable to normalize Yosys file path: " + path;
        return false;
    }
    normalizedPath = generic;
    return true;
}

bool ValidateRequest(const YosysScriptRequest& request, std::string& errorMessage) {
    if (request.sourceFiles.empty()) {
        errorMessage = "At least one RTL source file is required.";
        return false;
    }
    if (!IsValidVerilogIdentifier(request.topModule)) {
        errorMessage = "The top module is not a valid Verilog identifier.";
        return false;
    }
    if (!IsValidVerilogIdentifier(request.yosysFamily)) {
        errorMessage = "The target profile has an invalid Yosys family.";
        return false;
    }
    return true;
}

} // namespace

const StrategyInfo& GetStrategyInfo(YosysStrategy strategy) {
    switch (strategy) {
        case YosysStrategy::Baseline:          return kBaselineStrategy;
        case YosysStrategy::Debug:             return kDebugStrategy;
        case YosysStrategy::ResourceOptimized: return kResourceOptimizedStrategy;
    }
    return kBaselineStrategy;
}

bool ParseStrategy(const std::string& value, YosysStrategy& strategy) {
    if (value == kBaselineStrategy.id) {
        strategy = YosysStrategy::Baseline;
        return true;
    }
    if (value == kDebugStrategy.id) {
        strategy = YosysStrategy::Debug;
        return true;
    }
    if (value == kResourceOptimizedStrategy.id) {
        strategy = YosysStrategy::ResourceOptimized;
        return true;
    }
    return false;
}

YosysScriptResult YosysScriptGenerator::Generate(const YosysScriptRequest& request) const {
    YosysScriptResult result;
    if (!ValidateRequest(request, result.errorMessage)) {
        return result;
    }

    std::string outputPath;
    if (!NormalizeYosysPath(request.outputJsonPath, outputPath, result.errorMessage)) {
        return result;
    }

    const StrategyInfo& strategyInfo = GetStrategyInfo(request.strategy);
    std::string script = "# Generated by SigFlow.\n";
    script += "# Strategy: " + strategyInfo.id + "@" + strategyInfo.version + "\n";
    script += "# Target profile: " + request.targetProfileId + "@" +
              request.targetProfileVersion + "\n";

    for (const std::string& sourceFile : request.sourceFiles) {
        std::string sourcePath;
        if (!NormalizeYosysPath(sourceFile, sourcePath, result.errorMessage)) {
            return result;
        }
        const std::string lower = ToLower(sourceFile);
        script += "read_verilog";
        if (lower.size() >= 3 && lower.compare(lower.size() - 3, 3, ".sv") == 0) {
            script += " -sv";
        }
        script += " \"" + sourcePath + "\"\n";
    }

    script += "hierarchy -check -top " + request.topModule + "\n";
    switch (request.strategy) {
        case YosysStrategy::Baseline:
            break;
        case YosysStrategy::Debug:
            script += "check\n";
            break;
        case YosysStrategy::ResourceOptimized:
            script += "opt_clean\n";
            break;
    }
    script += "synth_gowin -family " + request.yosysFamily + " -top " + request.topModule + "\n";
    if (request.strategy == YosysStrategy::Debug) {
        script += "stat\n";
    }
    script += "write_json \"" + outputPath + "\"\n";

    result.success = true;
    result.script = script;
    return result;
}

} // namespace synth
} // namespace eda
