@echo off
chcp 65001 >nul
echo =========================================
echo  Verilator Windows 运行修复工具
echo =========================================
echo.

set MSYS2_PATH=C:\msys64
set TARGET_FILE=%MSYS2_PATH%\mingw64\bin\verilator.bat

echo 正在检查 MSYS2 安装...

if not exist "%MSYS2_PATH%\msys2.exe" (
    echo [错误] 未找到 MSYS2，请确保安装在 %MSYS2_PATH%
    pause
    exit /b 1
)

echo [OK] 找到 MSYS2
echo.
echo 正在创建 verilator.bat 包装器...

(
echo @echo off
echo @REM Verilator wrapper for Windows
echo @REM This file is auto-generated by SigFlow
echo "%MSYS2_PATH%\mingw64\bin\verilator_bin.exe" %%*
) > "%TARGET_FILE%"

if %errorLevel% neq 0 (
    echo [错误] 创建文件失败，请以管理员权限运行此脚本
echo.
    pause
    exit /b 1
)

echo [OK] 创建成功: %TARGET_FILE%
echo.
echo 测试 verilator 命令...
echo.

verilator --version

if %errorLevel% neq 0 (
    echo.
    echo [警告] 测试失败，请确保已添加环境变量：
    echo   C:\msys64\mingw64\bin
    echo   C:\msys64\usr\bin
    echo.
    echo 添加后请重新打开命令行窗口
) else (
    echo.
    echo =========================================
    echo  修复成功！
    echo =========================================
    echo.
    echo 现在可以直接使用 'verilator --version' 了
)

echo.
pause
