#include "SimMainGenerator.h"
#include <fstream>
#include <sstream>
#include <map>

SimMainGenerator::SimMainGenerator() {}
SimMainGenerator::~SimMainGenerator() {}

bool SimMainGenerator::Generate(const Timeline& timeline, const wxString& outputPath,
                                const wxString& vcdRelativePath)
{
    std::ofstream file(outputPath.ToStdString());
    if (!file.is_open()) {
        m_lastError = wxString::Format("无法创建文件: %s", outputPath);
        return false;
    }

    std::string code;
    code += GenerateIncludes(timeline);
    code += "\n\nint main(int argc, char** argv) {\n";
    code += GenerateInitialization(timeline);
    code += GenerateEventDriving(timeline);
    code += GenerateCleanup();
    code += "}\n";

    file << code;
    file.close();
    return true;
}

std::string SimMainGenerator::GenerateIncludes(const Timeline& timeline)
{
    std::ostringstream ss;
    ss << "// Auto-generated simulation main file\n";
    ss << "// Generated by SigFlow Simulation Engine\n\n";
    ss << "#include \"V" << timeline.topModuleName << ".h\"\n";
    ss << "#include \"verilated.h\"\n";
    ss << "#include \"verilated_vcd_c.h\"\n";
    ss << "#include <map>\n";
    ss << "#include <string>\n";
    return ss.str();
}

std::string SimMainGenerator::GenerateInitialization(const Timeline& timeline)
{
    std::ostringstream ss;
    ss << "    Verilated::commandArgs(argc, argv);\n";
    ss << "    Verilated::traceEverOn(true);\n\n";

    ss << "    // Create top module instance\n";
    ss << "    V" << timeline.topModuleName << "* top = new V" << timeline.topModuleName << ";\n\n";

    ss << "    // Initialize waveform trace\n";
    ss << "    VerilatedVcdC* tfp = new VerilatedVcdC;\n";
    ss << "    top->trace(tfp, 99);\n";
    ss << "    tfp->open(\"waveform/wave.vcd\");  // VCD output\n\n";

    ss << "    vluint64_t sim_time = 0;\n\n";

    ss << "    // Signal state tracking for edge detection\n";
    ss << "    std::map<std::string, bool> signalStates;\n\n";

    ss << "    // Initial evaluation\n";
    ss << "    top->eval();\n";
    ss << "    tfp->dump(sim_time);\n\n";

    return ss.str();
}

std::string SimMainGenerator::GenerateEventDriving(const Timeline& timeline)
{
    std::ostringstream ss;
    ss << "    // === Timeline event handling ===\n";
    ss << "    // Max simulation time: " << timeline.maxSimTime << "\n\n";

    // 将事件按时间分组
    std::map<uint64_t, std::vector<const TimelineEvent*>> eventsByTime;
    for (const auto& evt : timeline.events) {
        eventsByTime[evt.time].push_back(&evt);
    }

    uint64_t lastTime = 0;
    for (const auto& [time, events] : eventsByTime) {
        // 输出该时间点的所有事件
        bool hasAssignment = false;
        for (const auto* evt : events) {
            if (evt->signalName.empty()) {
                // 这是注释事件（如边沿等待标记）
                ss << "    // " << evt->comment << "\n";
                continue;
            }

            std::string cppValue = VerilogValueToCpp(evt->value);
            ss << "    // [" << time << "] " << evt->signalName << " = " << evt->value << "\n";
            ss << "    top->" << evt->signalName << " = " << cppValue << ";\n";
            hasAssignment = true;
        }

        if (hasAssignment) {
            // 如果需要从上一时间推进到当前时间
            if (time > lastTime && lastTime > 0) {
                ss << "\n    // 推进到时间 " << time << "\n";
                ss << "    while (sim_time < " << time << ") {\n";

                // 如果有时钟，在推进过程中翻转时钟
                if (timeline.clock.valid) {
                    ss << "        if (sim_time % " << timeline.clock.halfPeriod << " == 0) {\n";
                    ss << "            top->" << timeline.clock.signalName
                       << " = !top->" << timeline.clock.signalName << ";\n";
                    ss << "        }\n";
                }

                ss << "        top->eval();\n";
                ss << "        tfp->dump(sim_time);\n";
                ss << "        sim_time++;\n";
                ss << "    }\n\n";
            } else if (time > 0 && lastTime == 0) {
                ss << "\n    // 推进到时间 " << time << "\n";
                ss << "    while (sim_time < " << time << ") {\n";
                if (timeline.clock.valid) {
                    ss << "        if (sim_time % " << timeline.clock.halfPeriod << " == 0) {\n";
                    ss << "            top->" << timeline.clock.signalName
                       << " = !top->" << timeline.clock.signalName << ";\n";
                    ss << "        }\n";
                }
                ss << "        top->eval();\n";
                ss << "        tfp->dump(sim_time);\n";
                ss << "        sim_time++;\n";
                ss << "    }\n\n";
            }

            ss << "    top->eval();\n";
            ss << "    tfp->dump(sim_time);\n\n";
            lastTime = time;
        }
    }

    // 最后运行额外步骤以捕获所有变化
    uint64_t extraSteps = 100;
    if (timeline.clock.valid) {
        // 至少跑几个完整时钟周期
        extraSteps = std::max(extraSteps, timeline.clock.halfPeriod * 10);
    }

    ss << "    // Run additional steps\n";
    ss << "    for (int i = 0; i < " << extraSteps << "; i++) {\n";
    if (timeline.clock.valid) {
        ss << "        if (sim_time % " << timeline.clock.halfPeriod << " == 0) {\n";
        ss << "            top->" << timeline.clock.signalName
           << " = !top->" << timeline.clock.signalName << ";\n";
        ss << "        }\n";
    }
    ss << "        top->eval();\n";
    ss << "        tfp->dump(sim_time++);\n";
    ss << "    }\n\n";

    return ss.str();
}

std::string SimMainGenerator::GenerateCleanup()
{
    std::ostringstream ss;
    ss << "    // Close waveform file\n";
    ss << "    tfp->close();\n";
    ss << "    delete tfp;\n";
    ss << "    delete top;\n\n";
    ss << "    return 0;\n";
    return ss.str();
}

std::string SimMainGenerator::VerilogValueToCpp(const std::string& value)
{
    if (value.empty()) return "0";

    // 纯数字
    if (std::all_of(value.begin(), value.end(), ::isdigit)) {
        return value;
    }

    // Verilog 格式: N'bVALUE, N'hVALUE, N'dVALUE
    if (value.find('\'') != std::string::npos) {
        size_t quotePos = value.find('\'');
        char base = value[quotePos + 1];
        std::string digits = value.substr(quotePos + 2);

        switch (base) {
        case 'b': case 'B':
            return "0b" + digits;
        case 'h': case 'H':
            return "0x" + digits;
        case 'd': case 'D':
            return digits;
        default:
            return value;
        }
    }

    return value;
}
