#include "SimMainGenerator.h"
#include <fstream>
#include <sstream>
#include <map>

SimMainGenerator::SimMainGenerator() {}
SimMainGenerator::~SimMainGenerator() {}

bool SimMainGenerator::Generate(const Timeline& timeline, const wxString& outputPath,
                                const wxString& vcdRelativePath)
{
    std::ofstream file(outputPath.ToStdString());
    if (!file.is_open()) {
        m_lastError = wxString::Format(wxT("无法创建文件: %s"), outputPath);
        return false;
    }

    std::string code;
    code += GenerateIncludes(timeline);
    code += "\n\nint main(int argc, char** argv) {\n";
    code += GenerateInitialization(timeline);
    code += GenerateEventDriving(timeline);
    code += GenerateCleanup();
    code += "}\n";

    file << code;
    file.close();
    return true;
}

std::string SimMainGenerator::GenerateIncludes(const Timeline& timeline)
{
    std::ostringstream ss;
    ss << "// Auto-generated simulation main file\n";
    ss << "// Generated by SigFlow Simulation Engine\n\n";
    ss << "#include \"V" << timeline.topModuleName << ".h\"\n";
    ss << "#include \"verilated.h\"\n";
    ss << "#include \"verilated_vcd_c.h\"\n";
    ss << "#include <map>\n";
    ss << "#include <string>\n";
    return ss.str();
}

std::string SimMainGenerator::GenerateInitialization(const Timeline& timeline)
{
    std::ostringstream ss;
    ss << "    Verilated::commandArgs(argc, argv);\n";
    ss << "    Verilated::traceEverOn(true);\n\n";

    ss << "    // Create top module instance\n";
    ss << "    V" << timeline.topModuleName << "* top = new V" << timeline.topModuleName << ";\n\n";

    ss << "    // Initialize waveform trace\n";
    ss << "    VerilatedVcdC* tfp = new VerilatedVcdC;\n";
    ss << "    top->trace(tfp, 99);\n";
    ss << "    tfp->open(\"waveform/wave.vcd\");  // VCD output\n\n";

    ss << "    vluint64_t sim_time = 0;\n\n";

    ss << "    // Signal state tracking for edge detection\n";
    ss << "    std::map<std::string, bool> signalStates;\n\n";

    ss << "    // Initial evaluation\n";
    ss << "    top->eval();\n";
    ss << "    tfp->dump(sim_time);\n\n";

    return ss.str();
}

std::string SimMainGenerator::GenerateEventDriving(const Timeline& timeline)
{
    std::ostringstream ss;
    ss << "    // === Timeline event handling ===\n";
    ss << "    // Max simulation time: " << timeline.maxSimTime << "\n\n";

    std::string halfP = std::to_string(timeline.clock.halfPeriod);

    // 将事件按时间分组
    std::map<uint64_t, std::vector<const TimelineEvent*>> eventsByTime;
    for (const auto& evt : timeline.events) {
        eventsByTime[evt.time].push_back(&evt);
    }

    // 生成时钟推进代码块的 lambda（避免重复）
    auto emitAdvanceLoop = [&](uint64_t targetTime) {
        ss << "    // 推进到时间 " << targetTime << "\n";
        ss << "    while (sim_time < " << targetTime << ") {\n";
        ss << "        sim_time++;\n";
        if (timeline.clock.valid) {
            ss << "        if (sim_time % " << halfP << " == 0) {\n";
            ss << "            top->" << timeline.clock.signalName
               << " = !top->" << timeline.clock.signalName << ";\n";
            ss << "        }\n";
        }
        ss << "        top->eval();\n";
        ss << "        tfp->dump(sim_time);\n";
        ss << "    }\n\n";
    };

    uint64_t lastTime = 0;
    for (const auto& [time, events] : eventsByTime) {
        // 收集该时间点的赋值和注释
        std::vector<std::string> comments;
        std::vector<std::pair<std::string, std::string>> assignments; // signal, cppValue

        for (const auto* evt : events) {
            if (evt->signalName.empty()) {
                comments.push_back(evt->comment);
                continue;
            }
            assignments.emplace_back(evt->signalName, VerilogValueToCpp(evt->value));
        }

        if (assignments.empty() && comments.empty()) continue;

        // 先推进时间到目标时刻，再执行赋值
        if (time > lastTime) {
            emitAdvanceLoop(time);
        }

        // 输出注释
        for (const auto& c : comments) {
            ss << "    // " << c << "\n";
        }

        // 输出赋值
        for (const auto& [sig, val] : assignments) {
            ss << "    // [" << time << "] " << sig << " = " << val << "\n";
            ss << "    top->" << sig << " = " << val << ";\n";
        }

        if (!assignments.empty()) {
            ss << "    top->eval();\n";
            ss << "    tfp->dump(sim_time);\n\n";
            lastTime = time;
        }
    }

    // 最后运行额外步骤以捕获所有变化
    uint64_t extraSteps = 100;
    if (timeline.clock.valid) {
        extraSteps = std::max(extraSteps, timeline.clock.halfPeriod * 10);
    }

    ss << "    // Run additional steps\n";
    ss << "    for (vluint64_t i = 0; i < " << extraSteps << "; i++) {\n";
    ss << "        sim_time++;\n";
    if (timeline.clock.valid) {
        ss << "        if (sim_time % " << halfP << " == 0) {\n";
        ss << "            top->" << timeline.clock.signalName
           << " = !top->" << timeline.clock.signalName << ";\n";
        ss << "        }\n";
    }
    ss << "        top->eval();\n";
    ss << "        tfp->dump(sim_time);\n";
    ss << "    }\n\n";

    return ss.str();
}

std::string SimMainGenerator::GenerateCleanup()
{
    std::ostringstream ss;
    ss << "    // Close waveform file\n";
    ss << "    tfp->close();\n";
    ss << "    delete tfp;\n";
    ss << "    delete top;\n\n";
    ss << "    return 0;\n";
    return ss.str();
}

std::string SimMainGenerator::VerilogValueToCpp(const std::string& value)
{
    if (value.empty()) return "0";

    // 纯数字
    if (std::all_of(value.begin(), value.end(), ::isdigit)) {
        return value;
    }

    // Verilog 格式: N'bVALUE, N'hVALUE, N'dVALUE
    if (value.find('\'') != std::string::npos) {
        size_t quotePos = value.find('\'');
        char base = value[quotePos + 1];
        std::string digits = value.substr(quotePos + 2);

        switch (base) {
        case 'b': case 'B':
            return "0b" + digits;
        case 'h': case 'H':
            return "0x" + digits;
        case 'd': case 'D':
            return digits;
        default:
            return value;
        }
    }

    return value;
}
