#include "SimMainCodeGen.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>

namespace eda {
namespace sim {

SimMainGenerator::SimMainGenerator() = default;
SimMainGenerator::~SimMainGenerator() = default;

bool SimMainGenerator::Generate(const Timeline& timeline, const std::string& outputPath,
                                const std::string& /*vcdRelativePath*/) {
    std::ofstream file{std::filesystem::path(outputPath)};
    if (!file.is_open()) {
        lastError_ = "cannot create file: " + outputPath;
        return false;
    }
    std::string code;
    code += GenerateIncludes(timeline);
    code += "\n\nint main(int argc, char** argv) {\n";
    code += GenerateInitialization(timeline);
    code += GenerateEventDriving(timeline);
    code += GenerateCleanup();
    code += "}\n";
    file << code;
    file.close();
    return true;
}

std::string SimMainGenerator::GenerateIncludes(const Timeline& timeline) {
    std::ostringstream ss;
    ss << "// Auto-generated simulation main file\n";
    ss << "// Generated by SigFlow Simulation Engine\n\n";
    ss << "#include \"V" << timeline.topModuleName << ".h\"\n";
    ss << "#include \"verilated.h\"\n";
    ss << "#include \"verilated_vcd_c.h\"\n";
    ss << "#include <map>\n#include <string>\n";
    return ss.str();
}

std::string SimMainGenerator::GenerateInitialization(const Timeline& timeline) {
    std::ostringstream ss;
    ss << "    Verilated::commandArgs(argc, argv);\n";
    ss << "    Verilated::traceEverOn(true);\n\n";
    ss << "    V" << timeline.topModuleName << "* top = new V" << timeline.topModuleName << ";\n\n";
    ss << "    VerilatedVcdC* tfp = new VerilatedVcdC;\n";
    ss << "    top->trace(tfp, 99);\n";
    ss << "    tfp->open(\"waveform/wave.vcd\");\n\n";
    ss << "    vluint64_t sim_time = 0;\n\n";
    ss << "    std::map<std::string, bool> signalStates;\n\n";
    ss << "    top->eval();\n";
    ss << "    tfp->dump(sim_time);\n\n";
    return ss.str();
}

std::string SimMainGenerator::GenerateEventDriving(const Timeline& timeline) {
    std::ostringstream ss;
    ss << "    // === Timeline event handling ===\n";
    ss << "    // Max simulation time: " << timeline.maxSimTime << "\n\n";

    const std::string halfPeriod = std::to_string(timeline.clock.halfPeriod);

    std::map<std::uint64_t, std::vector<const TimelineEvent*>> eventsByTime;
    for (const auto& evt : timeline.events) eventsByTime[evt.time].push_back(&evt);

    const auto emitAdvanceLoop = [&](std::uint64_t targetTime) {
        ss << "    while (sim_time < " << targetTime << ") {\n";
        ss << "        sim_time++;\n";
        if (timeline.clock.valid) {
            ss << "        if (sim_time % " << halfPeriod << " == 0) {\n";
            ss << "            top->" << timeline.clock.signalName << " = !top->"
               << timeline.clock.signalName << ";\n";
            ss << "        }\n";
        }
        ss << "        top->eval();\n        tfp->dump(sim_time);\n    }\n\n";
    };

    std::uint64_t lastTime = 0;
    for (const auto& [time, events] : eventsByTime) {
        std::vector<std::string> comments;
        std::vector<std::pair<std::string, std::string>> assignments;
        for (const auto* evt : events) {
            if (evt->signalName.empty()) { comments.push_back(evt->comment); continue; }
            assignments.emplace_back(evt->signalName, VerilogValueToCpp(evt->value));
        }
        if (assignments.empty() && comments.empty()) continue;
        if (time > lastTime) emitAdvanceLoop(time);
        for (const auto& comment : comments) ss << "    // " << comment << "\n";
        for (const auto& [signal, value] : assignments) {
            ss << "    // [" << time << "] " << signal << " = " << value << "\n";
            ss << "    top->" << signal << " = " << value << ";\n";
        }
        if (!assignments.empty()) {
            ss << "    top->eval();\n    tfp->dump(sim_time);\n\n";
            lastTime = time;
        }
    }

    std::uint64_t extraSteps = 100;
    if (timeline.clock.valid) {
        extraSteps = std::max(extraSteps, timeline.clock.halfPeriod * 10);
    }
    ss << "    for (vluint64_t i = 0; i < " << extraSteps << "; i++) {\n";
    ss << "        sim_time++;\n";
    if (timeline.clock.valid) {
        ss << "        if (sim_time % " << halfPeriod << " == 0) {\n";
        ss << "            top->" << timeline.clock.signalName << " = !top->"
           << timeline.clock.signalName << ";\n";
        ss << "        }\n";
    }
    ss << "        top->eval();\n        tfp->dump(sim_time);\n    }\n\n";
    return ss.str();
}

std::string SimMainGenerator::GenerateCleanup() {
    std::ostringstream ss;
    ss << "    tfp->close();\n    delete tfp;\n    delete top;\n\n    return 0;\n";
    return ss.str();
}

std::string SimMainGenerator::VerilogValueToCpp(const std::string& value) {
    if (value.empty()) return "0";
    if (std::all_of(value.begin(), value.end(),
                    [](unsigned char c) { return std::isdigit(c) != 0; })) {
        return value;
    }
    if (value.find('\'') != std::string::npos) {
        const std::size_t quotePos = value.find('\'');
        const char base = value[quotePos + 1];
        const std::string digits = value.substr(quotePos + 2);
        switch (base) {
            case 'b': case 'B': return "0b" + digits;
            case 'h': case 'H': return "0x" + digits;
            case 'd': case 'D': return digits;
            default: return value;
        }
    }
    return value;
}

} // namespace sim
} // namespace eda
