// Generated by SigFlow DebugOverlayBuilder — do not edit.
// Session: tracebridge-tangnano9k-demo
module sf_debug_top(
    input  wire dbg_rx,
    output wire dbg_tx,
    output wire [3:0] led,
    input  wire rst_n,
    output wire uart_tx,
    input  wire clk
);
    wire dbg_rst_n = 1'b1;
    min_led_uart_top u_dut (
        .led(led),
        .rst_n(rst_n),
        .uart_tx(uart_tx),
        .clk(clk)
    );

    (* keep *) wire [31:0] probe_bus;
    assign probe_bus[3:0] = led;
    assign probe_bus[7:4] = u_dut.state;
    wire sample_clk = clk;

    wire arm, reset_pulse;
    wire [31:0] trigger_mask, trigger_value;
    wire [7:0] decimation;
    wire busy, done, triggered;
    wire [9:0] trigger_index;
    wire [9:0] rd_addr;
    wire [31:0] rd_data;

    wire [2:0] trigger_mode;
    wire [15:0] trigger_count;
    wire sample_en;
    wire hs_valid, hs_ready;

    assign hs_valid = 1'b0;
    assign hs_ready = 1'b1;

    sf_micro_ila #(.DEPTH(1024), .WIDTH(32)) u_ila (
        .clk(sample_clk), .rst_n(dbg_rst_n),
        .probe(probe_bus),
        .arm(arm),
        .trigger_mask(trigger_mask), .trigger_value(trigger_value),
        .trigger_mode(trigger_mode), .trigger_count(trigger_count),
        .decimation(decimation),
        .sample_en(sample_en), .hs_valid(hs_valid), .hs_ready(hs_ready),
        .busy(busy), .done(done), .triggered(triggered),
        .rd_addr(rd_addr), .rd_data(rd_data),
        .trigger_index(trigger_index)
    );

    sf_debug_link #(
        .CLK_HZ(27000000),
        .BAUD(921600),
        .WIDTH(32),
        .DEPTH(1024),
        .FINGERPRINT64(64'h0000000000000000),
        .IP_VERSION(1)
    ) u_link (
        .clk(sample_clk), .rst_n(dbg_rst_n),
        .rx(dbg_rx), .tx(dbg_tx),
        .arm_pulse(arm), .reset_pulse(reset_pulse),
        .trigger_mask(trigger_mask), .trigger_value(trigger_value),
        .decimation(decimation),
        .trigger_mode(trigger_mode), .trigger_count(trigger_count),
        .sample_en(sample_en),
        .busy(busy), .done(done), .triggered(triggered),
        .trigger_index(trigger_index),
        .rd_addr(rd_addr), .rd_data(rd_data)
    );
endmodule
